### ISSUE TITLE
Some users cannot see kennels on the Upcoming Runs page

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#315] opened 2022-05-02 20:35 UTC
Some users (specifically Mexican Rimjob, Quarter Cup) cannot see upcoming Rain City H3 events on their app "Upcoming Runs" screen. Mexican Rimjob is even listed in the app as a JGM, has admin permissions, and is a "permanent member" of the kennel. They could see other Seattle-area events on that list, just not for Rain City H3.

**Comment by diabWH3** [comment] 2022-05-02 20:54
Screenshot below is from MRJ's app using Android v1.0.76, Build #549 with location services turned on. You can see the "Kennels" screen does not offer him the option to "Sort by Distance." On the "Explore Runs" map, he **can** use the "my location" feature and it shows a blue dot at his actual location. So it seems the app can only access his location on an intermittent basis, or at least for only certain functions.

![2022-05-02 (1)](https://user-images.githubusercontent.com/49632769/166325651-d89cfbb4-0bbc-4abe-a95e-8332708e16e3.png)

**Comment by James-A-White** [comment] 2022-05-04 19:53
That's strange...  I may have to clone his account to see if I can replicate this. I'll try to poke around a bit on this next week. In the meantime, could you ask if he would mind deleting and reloading the app and ensuring that he allows location permissions on the first entry screens. I'm thinking that the issue could materialize if he originally asked for it to not use location services and then he switched it on later. Thanks!

**Comment by diabWH3** [comment] 2022-05-06 21:38
That appears to have worked; it must be related to denying Location
Services upon first install and then turning them on later.

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*

**Comment by diabWH3** [comment] 2022-05-10 01:02
The user, Mexican Rimjob, can now see upcoming runs, but the automatic
PayPal button does not show, despite standing at the trail start location
(specifically SeaMon H3 #345).

---
Joshua Johnson
352.538.7567

**Comment by James-A-White** [comment] 2022-06-29 20:57
I think this was because he did not have location services turned on. Can you confirm that this was the case? Once he turned on location services, the automatic pay button should now appear. Once you confirm, I'll close this issue.

**Comment by diabWH3** [comment] 2022-06-29 22:09
I believe we *did* confirm he turned Location Services on again. That fixed
the list of upcoming runs, but did not show the "Pay with PayPal" button
that shows up for both Rain City H3 and SeaMon H3.
I'll attempt to remember to bug him next Monday when SeaMon runs next.

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*

**Comment by James-A-White** [comment] 2023-03-04 10:42
Closing this one now...  I assume it's working as designed at this point.

**Closed by James-A-White** 2023-03-04 10:42 UTC
